version: '3.8'

services:
  documents:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ../wwwroot:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
