version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: prontuari-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    networks:
      - mongo-network
  documents:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ../wwwroot:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
  
networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local